/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JPALAB;



import java.sql.Date;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import com.Ticket;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("TicketPU");
		EntityManager entitymanager = emf.createEntityManager();
		Ticket ticket = new Ticket();
		ticket.setSource("SarkaruVaariPaata Movie");
		ticket.setDestination("Lakshmi Teather");
		ticket.setPrice(200);
		ticket.setDate(new Date(2022, 04, 9));
		
		entitymanager.getTransaction().begin();
		entitymanager.persist(ticket);
		entitymanager.flush();
		entitymanager.getTransaction().commit();
	}
}
